manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: petejohanson # <-- enable the drivers FOR CIRQUE
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # support nice_oled and nice_epaper
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    #support for CIRQUE
    - name: cirque-input-module # <-- enable the drivers
      remote: petejohanson
      revision: main
    - name: zmk-cirque-adapter # <-- enable this module
      remote: mctechnology17
      revision: main
  self:
    path: config