manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    #petejohanson is a ZMK dev
    - name: petejohanson
      url-base: https://github.com/petejohanson
    #pm0u refrences pete for the cirque trackpad
    - name: pm0u
      url-base: https://github.com/pm0u

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # support nice_oled and nice_epaper
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    #pete is a ZMK dev.
    - name: cirque-input-module
      remote: petejohanson
      revision: main
    #pm0u cirque section that uses pete
    - name: glidepoint_i2c
      remote: pm0u
      revision: main
      path: modules/glidepoint_i2c
  self:
    path: config